import type { AITool } from '@/lib/utilities/types'

export const sampleTools: AITool[] = [
  {
    id: '1',
    name: 'Synthesia',
    slug: 'synthesia',
    tagline: 'AI Video Generation Platform',
    description:
      'Create professional videos with AI avatars in 120+ languages without filming',
    logo: '🎬',
    website: 'https://synthesia.io',
    category: 'Video',
    subCategories: ['Avatar Creation', 'Video Marketing', 'Training Videos'],
    pricing: 'Paid',
    startingPrice: 29,
    pricingTiers: [
      {
        name: 'Starter',
        price: 29,
        interval: 'monthly',
        features: ['10 minutes/month', '70+ AI avatars', '120+ languages'],
        limits: { apiCalls: 0 },
        highlighted: false,
      },
      {
        name: 'Creator',
        price: 89,
        interval: 'monthly',
        features: [
          '30 minutes/month',
          'Custom avatars',
          'API access',
          'Priority support',
        ],
        limits: { apiCalls: 1000 },
        highlighted: true,
      },
    ],
    aiModels: [{ name: 'Proprietary', provider: 'Proprietary' }],
    features: [
      {
        id: '1',
        title: 'AI Avatars',
        description: '140+ diverse AI avatars',
        category: 'core',
        available: true,
      },
      {
        id: '2',
        title: 'Voice Cloning',
        description: 'Clone your own voice',
        category: 'advanced',
        available: true,
      },
      {
        id: '3',
        title: 'Custom Backgrounds',
        description: 'Upload custom backgrounds',
        category: 'core',
        available: true,
      },
    ],
    integrations: [
      { name: 'Slack', type: 'webhook' },
      { name: 'YouTube', type: 'native' },
    ],
    hasApi: true,
    apiDocUrl: 'https://docs.synthesia.io',
    compliance: {
      gdpr: true,
      ccpa: true,
      soc2: true,
      hipaa: false,
      iso27001: true,
    },
    stats: {
      totalUsers: 50000,
      founded: 2017,
    },
    rating: 4.7,
    reviewCount: 2341,
    pros: ['Easy to use', 'Great avatar quality', 'Multi-language support'],
    cons: [
      'Limited customization',
      'Can look artificial',
      'Expensive for high volume',
    ],
    useCases: [
      'Training videos',
      'Marketing content',
      'Internal communications',
    ],
    alternatives: ['2', '3'],
    lastUpdated: '2024-10-15T00:00:00.000',
    tags: ['video', 'avatars', 'multilingual', 'enterprise'],
  },
  {
    id: '2',
    name: 'Claude',
    slug: 'claude',
    tagline: 'Advanced AI Assistant by Anthropic',
    description:
      'Powerful AI assistant for writing, analysis, coding, and math with 200K context window',
    logo: '🤖',
    website: 'https://claude.ai',
    category: 'Chatbot',
    subCategories: ['Writing', 'Coding', 'Research'],
    pricing: 'Freemium',
    startingPrice: 0,
    pricingTiers: [
      {
        name: 'Free',
        price: 0,
        features: ['Limited messages', 'Claude 3.5 Sonnet', 'Basic features'],
        limits: { apiCalls: 0 },
      },
      {
        name: 'Pro',
        price: 20,
        interval: 'monthly',
        features: [
          '5x more usage',
          'Claude 3 Opus',
          'Priority access',
          'Projects',
        ],
        highlighted: true,
      },
    ],
    aiModels: [
      { name: 'Claude 3.5', version: 'Sonnet', provider: 'Anthropic' },
    ],
    features: [
      {
        id: '1',
        title: '200K Context',
        description: 'Process entire books',
        category: 'unique',
        available: true,
      },
      {
        id: '2',
        title: 'Code Analysis',
        description: 'Debug and write code',
        category: 'core',
        available: true,
      },
    ],
    integrations: [{ name: 'API', type: 'api' }],
    hasApi: true,
    compliance: {
      gdpr: true,
      ccpa: true,
      soc2: true,
      hipaa: false,
      iso27001: false,
    },
    stats: { totalUsers: 1000000, founded: 2021 },
    rating: 4.9,
    reviewCount: 8923,
    pros: ['Excellent reasoning', 'Great for coding', 'Ethical and safe'],
    cons: ['No image generation', 'Limited availability'],
    useCases: ['Code generation', 'Content writing', 'Research assistance'],
    alternatives: ['3'],
    lastUpdated: '2024-10-20T00:00:00.000',
    tags: ['chatbot', 'coding', 'writing', 'research'],
  },
  {
    id: '3',
    name: 'Midjourney',
    slug: 'midjourney',
    tagline: 'AI Image Generation',
    description: 'Create stunning AI-generated images from text prompts',
    logo: '🎨',
    website: 'https://midjourney.com',
    category: 'Image Generation',
    subCategories: ['Art', 'Design', 'Photography'],
    pricing: 'Paid',
    startingPrice: 10,
    pricingTiers: [
      {
        name: 'Basic',
        price: 10,
        interval: 'monthly',
        features: ['200 generations/month', 'General commercial terms'],
        limits: { apiCalls: 0 },
      },
    ],
    aiModels: [{ name: 'Midjourney V6', provider: 'Proprietary' }],
    features: [
      {
        id: '1',
        title: 'Style Control',
        description: 'Fine-tune artistic styles',
        category: 'core',
        available: true,
      },
    ],
    integrations: [{ name: 'Discord', type: 'native' }],
    hasApi: false,
    compliance: {
      gdpr: false,
      ccpa: false,
      soc2: false,
      hipaa: false,
      iso27001: false,
    },
    stats: { totalUsers: 16000000, founded: 2022 },
    rating: 4.8,
    reviewCount: 12453,
    pros: ['Stunning quality', 'Artistic flexibility'],
    cons: ['Discord-only interface', 'Learning curve'],
    useCases: ['Concept art', 'Marketing visuals', 'Creative exploration'],
    alternatives: ['1'],
    lastUpdated: '2024-10-18T00:00:00.000Z',

    tags: ['image', 'art', 'creative', 'design'],
  },
]
